#!/usr/bin/env python3

import pandas as pd
from table_query import TableQuery
from text_query import TextQuery
from semantic_search import SemanticSearch
from result import *
from cornwall_ai import CornwallAI

print("Loading...")

ai = CornwallAI()

# Set of questions to ask
questions = [
    "Which county is Bude in?",
    "What is the county town of Cornwall?",
    "How do you make a souffle?",
    "How do you start a revolution?",
    "What is the population of Helston in Cornwall",
    "Which Cornish towns have populations more than 20000?",
]

print("Asking questions...")

# Ask questions and show all results
print()
for q in questions:
    ans = ai.query(q)
    print("Q:", q)

    for an in ans:
        an.show()

    print()

